version: 0.2

env:
  variables:
    AWS_REGION_2: "us-east-2"
    AWS_REGION : "us-east-1"
    $AWS_ACCOUNT_ID : "767466983442"
    REACT_APP_API_SERVICE_URL: "http://flask-react-alb-1044593825.us-east-1.elb.amazonaws.com"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - docker login -u $username -p $password
      - echo logging in to ecr...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767466983442.dkr.ecr.us-east-1.amazonaws.com
      - echo logged in ...
  build:
    commands:
      - echo building dev images...
      - docker-compose up -d --build
      - echo building prod images...
      - >
        docker build \
          -f be/Dockerfile \
          -t 767466983442.dkr.ecr.us-east-1.amazonaws.com/twtr-be:prod \
          ./be
      - >
        docker build \
          -f fe/Dockerfile \
          -t 767466983442.dkr.ecr.us-east-1.amazonaws.com/twtr-fe:prod \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_API_SERVICE_URL=$REACT_APP_API_SERVICE_URL \
          ./fe
  post_build:
    commands:
    - echo pushing prod images to ecr...
    - docker push 767466983442.dkr.ecr.us-east-1.amazonaws.com/twtr-be:prod
    - docker push 767466983442.dkr.ecr.us-east-1.amazonaws.com/twtr-fe:prod
